msgid ""
msgstr ""
"Project-Id-Version: oVirt Client\n"
"POT-Creation-Date: 2016-10-22 17:49+0100\n"
"PO-Revision-Date: 2016-10-22 17:55+0100\n"
"Last-Translator: Nicol√°s Kovac Neumann <nicolas@devels.es>\n"
"Language-Team: nicolas@devels.es\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.7.1\n"
"X-Poedit-KeywordsList: _;gettext;gettext_noop\n"
"X-Poedit-Basepath: .\n"
"X-Poedit-SearchPath-0: /home/nico/ovirt_client/ovirt_client\n"

#: /home/nico/ovirt_client/ovirt_client/about.py:51
#: /home/nico/ovirt_client/ovirt_client/credentials.py:90
#: /home/nico/ovirt_client/ovirt_client/credentials.py:94
#: /home/nico/ovirt_client/ovirt_client/credentials.py:164
#: /home/nico/ovirt_client/ovirt_client/credentials.py:178
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:265
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:274
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:280
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:282
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:286
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:288
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:372
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:390
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:409
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:414
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:417
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:419
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:457
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:462
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:599
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:819
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:866
msgid "apptitle"
msgstr "oVirt desktop client"

#: /home/nico/ovirt_client/ovirt_client/about.py:53
msgid "appdesc"
msgstr "A simple oVirt desktop client"

#: /home/nico/ovirt_client/ovirt_client/about.py:56
msgid "written_by"
msgstr "Written by"

#: /home/nico/ovirt_client/ovirt_client/about.py:58
msgid "unofficial_project"
msgstr "This project is unofficial!"

#: /home/nico/ovirt_client/ovirt_client/about.py:63
#: /home/nico/ovirt_client/ovirt_client/credentials.py:228
msgid "ok"
msgstr "OK"

#: /home/nico/ovirt_client/ovirt_client/about.py:84
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:148
msgid "about"
msgstr "About"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:63
msgid "loading"
msgstr "Loading..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:79
msgid "authenticating"
msgstr "Authenticating..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:87
msgid "authenticated_and_storing"
msgstr "Authenticated, storing credentials..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:90
#: /home/nico/ovirt_client/ovirt_client/credentials.py:94
#: /home/nico/ovirt_client/ovirt_client/credentials.py:164
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:274
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:372
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:414
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:417
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:599
msgid "error"
msgstr "Something bad happened..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:90
msgid "ovirt_connection_error"
msgstr "oVirt connection error"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:91
#: /home/nico/ovirt_client/ovirt_client/credentials.py:95
msgid "error_while_authenticating"
msgstr "Error while authenticating"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:94
msgid "ovirt_request_error"
msgstr "oVirt request error"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:106
msgid "storing_credentials"
msgstr "Credentials"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:112
msgid "successfully_authenticated"
msgstr "Successfully authenticated"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:164
msgid "no_empty_creds"
msgstr ""
"Neither username or password might be blank. Please, enter your oVirt "
"credentials."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:178
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:457
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:819
msgid "confirm"
msgstr "Confirm"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:178
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:819
msgid "confirm_quit"
msgstr "Are you sure you want to quit?"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:212
msgid "username"
msgstr "Username"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:214
msgid "password"
msgstr "Password"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:225
msgid "remember_username_and_password"
msgstr "Remember username and password"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:231
msgid "cancel"
msgstr "Cancel"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:260
msgid "credentials"
msgstr "Credentials"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:85
msgid "no_vms"
msgstr ""
"You have currently no permissions over machines on this oVirt infrastructure"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:136
msgid "refresh"
msgstr "Refresh"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:141
msgid "forget_credentials"
msgstr "Forget credentials"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:153
msgid "exit"
msgstr "Exit"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:204
msgid "up"
msgstr "up"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:206
msgid "down"
msgstr "down"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:208
msgid "powering_down"
msgstr "powering down"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:210
msgid "wait_for_launch"
msgstr "waiting for launch"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:212
msgid "powering_up"
msgstr "powering up"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:226
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:243
msgid "shut_down"
msgstr "shut down"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:228
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:245
msgid "power_on"
msgstr "power on"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:240
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
msgid "current_vm_status"
msgstr "Current virtual machine status is"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:243
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:245
msgid "click_to_action"
msgstr "Click to"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:265
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:282
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:288
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:390
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:419
msgid "warning"
msgstr "Warning"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:265
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:282
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:288
msgid "vm_in_unchangeable_status"
msgstr ""
"Cannot change virtual machine status since it is already performing a power "
"on/shutdown task"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
msgid "confirm_vm_status_change"
msgstr "Please, confirm virtual machine status change to"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:274
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:414
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:599
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:731
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:743
msgid "unexpected_connection_drop"
msgstr "Connection has been closed unexpectedly. App will close."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:280
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:286
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:462
msgid "success"
msgstr "Success"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:280
msgid "shutting_down_vm"
msgstr "Shutting down machine..."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:286
msgid "powering_up_vm"
msgstr "Powering up machine..."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:372
msgid "no_viewer_file"
msgstr "Could not get viewer configuration file. Please, try again."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:390
msgid "cannot_connect_if_vm_not_up"
msgstr ""
"Cannot start virtual machine if status is not Up. Make sure VM is started "
"first."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:409
msgid "info"
msgstr "Information"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:409
msgid "acquiring_vm_from_pool"
msgstr ""
"Allocating a VM from the VmPool. Please be patient. Once the VM is "
"available, it will automatically appear in your dashboard."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:417
msgid "cannot_attach_vm_to_user"
msgstr ""
"Cannot allocate a VM. Either you already have the maximum of assignable VMs "
"or there are no machines left in the VmPool."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:419
msgid "object_is_not_a_vmpool"
msgstr "Selected object is not a VmPool."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:457
msgid "confirm_forget_creds"
msgstr "Do you really want to forget your stored credentials?"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:462
msgid "creds_forgotten"
msgstr "Credentials successfully dropped"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:480
msgid "vmpool"
msgstr "Virtual machines pool"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:488
msgid "grab_vm_vmpool"
msgstr "Allocate virtual machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:535
msgid "connect"
msgstr "Connect to the virtual machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:616
msgid "total_machines"
msgstr "Number of machines"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:616
msgid "total_vmpools"
msgstr "Number of VmPools"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:662
msgid "auto_logout_warn"
msgstr ""
"If you don't accept this window, you'll be automatically logged out the "
"session within a short amount of time due to inactivity"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:663
msgid "auto_logout_warn_title"
msgstr "oVirt desktop client: Enforced auto-logout"
